language: python

python:
  - 3.5

services:
  - docker

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=baton --cover-inclusive --tests baton/tests, baton/tests/_baton

after_success:
  - codecov
