language: python

python:
  - 3.5

services:
  - docker

env:
  global:
    - DOCKER_HOST="tcp://127.0.0.1:2375"
    - DOCKER_TLS_VERIFY=""
    - DOCKER_CERT_PATH=""

before_install:
  - pip install codecov
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::=--force-confdef docker-engine

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - docker build -t agaveapi/irods:3.3.1 -f 3.3.1/Dockerfile github.com/wtsi-hgi/docker-icat.git

script:
  - nosetests -v --with-coverage

after_success:
  - codecov
